### ISSUE TITLE
DIR variable seems to be wrong

### ISSUE THREAD

**Issue by ivanovaleksey** [mcornella/dotfiles#2]
Hi Marc!
Thank you for the nice repo.

I didn't fork the repo but I tried to fetch `init.zsh`.
I have problem with `DIR` variable

```
DIR=${0#~/}
echo $DIR # => ./init.zsh
```

So I have to change `DIR` variable like this

```
abs_path=${0:a:h}
DIR=${abs_path#~/}
echo $DIR # => projects/dotfiles
```

Is it something wrong with my zsh environment?
Does it work for you?

**Comment by mcornella** [comment]
Yeah I've wrestled with that many times. Let me check that later but it seems your solution is correct.

Thanks for checking it out!

**Comment by ivanovaleksey** [comment]
I would like to make it one-liner but I can't. Hence I added this `abs_path` variable.

**Comment by mcornella** [comment]
You can chain several `${}` expressions. So the final line is `DIR="${${0:a:h}#~/}"`. Thanks for noticing!

**Comment by ivanovaleksey** [comment]
I thought about chaining but I thought it would be wrong :disappointed: 
Thank you!
